### ISSUE TITLE
Projx Bug

### ISSUE THREAD

**Issue by isaykatsman** [dalab/matrix-manifolds#1]
Hi all,

It appears for some of the non-inplace projx operations, there may be a bug. In particular for the Grassmanian and SPD manifolds (see https://github.com/dalab/matrix-manifolds/blob/master/graphembed/graphembed/manifolds/grassmann.py#L60, https://github.com/dalab/matrix-manifolds/blob/master/graphembed/graphembed/manifolds/spd.py#L127). Instead of `return x` the return statement should be `return x_new`.

Best,
Isay

**Comment by calincru** [comment]
Fixed (see https://github.com/dalab/matrix-manifolds/commit/268feb0778dfc873b95f91b1c1c9740420cf190a), thanks for pointing it out.

It doesn't affect our results because we always used ```inplace=True``` when stabilizing after a gradient step: 
https://github.com/dalab/matrix-manifolds/blob/268feb0778dfc873b95f91b1c1c9740420cf190a/graphembed/graphembed/modules.py#L19
